---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-app
  namespace: {{ .Values.namespace }}
  labels:
    app: blue-green-app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: blue-green-app
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
      - name: blue-green-app
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: 3000
        env:
        - name: APP_COLOR
          value: {{ .Values.global.clusterRole }}
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: blue-green-app
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: blue-green-tgb
  namespace: {{ .Values.namespace }}
spec:
  serviceRef:
    name: blue-green-service
    port: 3000
  targetGroupARN: {{ .Values.target_group_arn }}
  targetType: ip
